/* 39.png and 39-2.png: counterfeit blades, potion bargaining, fur room, letters, duel and confession.
   Uncaptured transitions are reconstructed with the event order at wonavy.tistory.com/231. */
(()=>{
 const x=ARPIA_EXTRA,m=ARPIA_MIDTERM,h=ARPIA_WAR_HELPERS,I='assets/items/';
 for(const[id,name,icon]of [['swords39','미로에서 주운 모조 검들','assets/silent-sword.png'],['fur39','헝거의 흰 털','assets/midterm/fur23.png'],['claw39','악마의 발톱',I+'wolf_fang.png'],['disguise39','데빌아이 변신 물약',I+'potion.png'],['seal39','되찾은 데런 왕국의 옥새',I+'goldnugget.png']])ARPIA_DATA.ITEMS['mt_'+id]={name,desc:name,kind:'quest',price:0,sell:0,icon};
 Object.assign(x.npcs,{galli39:{name:'검 장인 갈리'},kelly39:{name:'켈리'},fur39:{name:'하얀 동물의 털',artPath:'assets/midterm/fur23.png',height:30},claw39:{name:'악마의 발톱',artPath:I+'wolf_fang.png',height:28},hideout39:{name:'헝거의 집 옆',artPath:I+'wood_chip.png',height:30},seal39:{name:'데런의 옥새',artPath:I+'goldnugget.png',height:30},disguise39:{name:'변신 준비',artPath:I+'potion.png',height:30}});
 const r=(key,title,scene,npc,lines,extra={})=>({key,title,scene,npc,lines,...extra});
 const rows=[
 r('aaron','전쟁을 멈추라는 당부','campus','aaron29',[['aaron29','교장 선생님은 두 나라가 화해할 수 있도록 원인을 끝까지 찾으라고 하셨다.'],['you','검 하나로는 부족해요. 미로를 다시 살펴봐야겠어요.'],['aaron29','서두르되 결론부터 정하지는 말거라.']]),
 r('search','미로 북서쪽의 흔적','derenmaze38','mazeGuard38',[['you','다른 갈림길에도 발자국이 있어요. 저 몬스터들 뒤를 살펴보죠.'],['aaron29','검을 찾더라도 어디에 놓여 있었는지 기억해 두거라.']],{fixture:true,pos:[180,120],battle:'maze39'}),
 r('swords','같은 모양의 검들','derenmaze38','sword38',[['narrator','떨어져 있는 검들은 모두 같은 장식과 굽은 날을 지니고 있었다.'],['you','하나가 아니라 여러 개예요. 누가 이 검을 만드는지부터 알아보죠.'],['aaron29','난쟁이 광산의 발디라면 솜씨를 알아볼지도 모른다.']],{fixture:true,pos:[180,250],effect:s=>m.give(s,'swords39')}),
 r('baldi','광산에서 만든 검이 아니다','mine','baldi',[['baldi','으음… 이건 수공예 검이야. 아주 훌륭하게 멋지게 만든 검이네.'],['baldi','우리 광산에서는 대량으로 검을 만들지. 이런 건 만들지 않아.'],['you','그럼 어떤 장인에게 물어보면 될까요?'],['baldi','아수리아의 검 장인인 갈리다.']]),
 r('galli','끝마무리가 다른 모조품','asuria','galli39',[['galli39','음… 이건 내가 만드는 전통 검의 모조품이군.'],['you','데런 왕국의 미로에서 발견됐어요. 아수리아 첩자의 증거라고 하는데요.'],['galli39','내가 만든 검은 끝마무리가 이렇지 않아. 생김새만 보고 판단해서는 곤란하지.'],['you','누군가 아수리아의 검처럼 보이게 만든 거군요.']]),
 r('battlefield','격전지의 두 선생님','dragonValley39','esta',[['esta','이대로 있다간 웨일라 대륙이 붕괴되겠어.'],['ryoma','양쪽 모두 물러날 생각을 하지 않아. 주민들을 피신시키는 데도 한계가 있다.'],['you','검 장인이 모조품이라고 했어요. 그 사실을 전하면 싸움을 잠시 멈출 수 있지 않을까요?'],['esta','카디쟈에게 먼저 말해 보렴. 그동안 우리는 이곳을 지키겠다.']]),
 r('scoll','길을 막은 스콜','cardiahome','scoll',[['scoll','난 사랑을 위해 명예와 지위를 버릴 준비가 다 되어 있다.'],['you','선생님을 설득하러 온 게 아니라 위조된 증거를 알리러 왔어요.'],['scoll','카디쟈님을 곤란하게 할 생각이라면 용납 못 한다!']],{battle:'scoll39'}),
 r('cardiaRequest','아수리아의 휴전 조건','cardiahome','cardia',[['cardia','모조품이라는 말은 알겠습니다. 휴전을 원한다면 고급 체력 물약 열 개를 가져오세요.'],['you','물약만 드리면 공격을 멈추는 거죠?'],['cardia','늑대의 도시 근처에 있는 몬스터들을 잡으면 그런 체력 물약이 나올 겁니다.'],['you','상점에서 구한 것도 같은 약이니까, 빠른 쪽으로 마련할게요.']]),
 r('cardiaDelivery','아수리아의 휴전','cardiahome','cardia',[['cardia','알겠습니다. 이를 받고 휴전을 하도록 하지요.'],['you','약속을 꼭 지켜 주세요. 진짜 범인을 곧 찾아내겠어요.']],{goal:'슈퍼체력물약(고급 체력 물약) 10개를 카디쟈에게 전달',effect:s=>{ARPIA_SYS.inv.remove(s,'hipotion',10);s.asuriaTruce39=true;}}),
 r('derenRequest','데런에서도 같은 요구','kingdom','matilda',[['matilda','에드워드 경도 고급 체력 물약 열 개가 필요하대. 가져오면 공격을 잠시 멈출 수 있어.'],['you','왜 양쪽에서 똑같은 약을 찾는 거지?'],['matilda','부상자가 많잖아. 휴전을 원한다면서?']]),
 r('derenDelivery','데런의 휴전','kingdom','edward',[['edward','물약 열 개, 확인했네. 약속대로 진격을 멈추겠다.'],['you','왜 다들 고급 체력 물약을 원하는 거지… 좀 이상한데.']],{goal:'슈퍼체력물약(고급 체력 물약) 10개를 에드워드에게 전달',effect:s=>{ARPIA_SYS.inv.remove(s,'hipotion',10);s.derenTruce39=true;}}),
 r('truce','휴전은 끝이 아니다','dragonValley39','esta',[['you','양쪽 모두 같은 물약 열 개를 받고 쉽게 휴전했어요. 뭔가 이상해요.'],['esta','고급 체력 물약을 마법사가 아닌 보통의 인간이 사용하면 무적의 전사가 될 수 있단다.'],['ryoma','그렇다면 약속을 지키는 동안에도 다음 싸움을 준비할 수 있겠군.'],['you','시간을 벌었을 뿐이네요. 배후를 밝혀야 정말 끝낼 수 있겠어요.']]),
 r('counterfeiter','블랙 마켓의 이름','asuria','galli39',[['you','이렇게 정교한 모조품을 만들 만한 사람이 누굴까요?'],['galli39','그는 블랙 마켓으로 불리네. 마법 약이나 복제품 같은 것들을 만드는 사람이지.'],['galli39','그는 켈리라네.'],['you','마법사의 도시로 가 볼게요. 검의 출처를 꼭 밝혀야 해요.']]),
 r('kelly','말 대신 알려 준 좌표','magecity','kelly39',[['kelly39','나야, 수중 던전의 맨 왼쪽 위에서 아래로 세 번째, 오른쪽으로 네 번째 방이에요.'],['you','누가 주문했는지 그 방에 가면 알 수 있다는 뜻이죠?'],['kelly39','내가 해 줄 이야기는 거기까지예요.']]),
 r('fur','수중 방에 떨어진 흰 털','diveroom15','fur39',[['you','제일 왼쪽 위에서 아래로 세 번째, 오른쪽으로 네 번째 방이랬지… 출발하자.'],['narrator','방 한쪽 바닥에 하얀 털이 엉겨 있었다.'],['you','이건 어디서 본 적이 있는 것 같은데… 동물의 털이야. 헝거의 털과 똑같아.']],{fixture:true,goal:'수중 던전 위에서 세 번째 줄, 왼쪽 네 번째 방 조사',effect:s=>m.give(s,'fur39')}),
 r('eavesdrop','집 밖으로 새어 나온 혼잣말','wolfcity31','hideout39',[['narrator','헝거의 집 옆에서 발소리를 죽였다. 안쪽에서 낮게 으르렁거리는 목소리가 들렸다.'],['hunger','그 꼬마, 눈치가 너무 빨라. 데빌아이를 만나 봐야겠어.'],['you','둘이 꾸민 일이었구나. 들키기 전에 서문으로 가 보자.']],{fixture:true}),
 r('west','서문에서 만난 두 범인','westgate39','devileye35',[['hunger','데빌아이! 왜 나타나지 않는 거야. 혼자서 시간 낭비만 하고 있잖아.'],['devileye35','너는 {name}. 잘 됐다. 이 자리에서 널 죽이고 비밀을 감추어 주마.'],['you','위조 검을 미로에 놓은 것도 너희지? 더는 도망갈 생각 하지 마!']],{battle:'villains39'}),
 r('suspects','아직 부족한 증거','westgate39','hunger',[['hunger','옥새를 훔치고 아수리아 검을 흘려 두니 서로 의심하더군. 계획은 이미 시작됐다!'],['you','둘이 싸우는 동안 너희는 무엇을 하려는 거지?'],['devileye35','그걸 네게 전부 설명할 필요는 없지.'],['narrator','두 범인은 연기 사이로 빠져나갔다. 이야기를 들었어도 두 왕국을 납득시킬 증거는 남지 않았다.']]),
 r('morris','직접 듣게 할 방법','principal','morris',[['morris','두 나라 모두 자존심을 걸고 싸웠다. 너의 말만으로 물러서기는 어려울 게다.'],['you','스콜 선생님과 마틸다가 헝거의 말을 직접 들으면 어떨까요?'],['morris','범인이 두 사람 앞에서도 사실대로 말하겠느냐?'],['you','좋은 생각이 났어. 바로 데빌아이로 변신하는 거야.']]),
 r('joker','악마의 발톱이 필요한 변신','magecity','joker',[['joker','동료의 모습으로 속여서 말을 끌어내겠다고? 위험하지만 가능은 하네.'],['you','이번에는 보석의 힘을 빌릴 필요는 없죠?'],['joker','악마의 발톱을 구해 오게. 데런 왕국의 미로에서 찾아볼 수 있을 걸세.']]),
 r('claw','미로 서쪽의 악마의 발톱','derenmaze38','claw39',[['narrator','미로 서쪽 길의 풀숲에서 보랏빛 발톱을 찾았다.'],['you','악마의 발톱이다. 조커에게 돌아가자.']],{fixture:true,pos:[180,390],effect:s=>m.give(s,'claw39')}),
 r('potion','데빌아이 변신 물약','magecity','joker',[['joker','다 됐네. 바로 마시지는 말게. 사람들이 숨을 곳부터 정해야 하니까.'],['you','먼저 편지를 보내 같은 곳으로 부를게요.'],['joker','모습만 같아질 뿐이야. 천리안까지 생기는 건 아니니 말을 조심하게.']],{requires:{claw39:1},effect:s=>{m.take(s,'claw39');m.give(s,'disguise39');}}),
 r('letters','미로로 부르는 세 통의 편지','shop','conrad',[['you','마틸다에게. 이번 전쟁의 배후를 밝혀냈어. 증거를 보여 줄 테니 데런 왕국의 미로로 와.'],['you','스콜 선생님. 전쟁의 배후를 밝혀냈어요. 증거를 보여 줄 테니 데런 왕국의 미로로 오세요.'],['narrator','헝거에게는 데빌아이의 이름으로 만나자는 편지를 보냈다.'],['conrad','세 통 모두 다른 수신인에게 보내겠습니다. 서로 다른 이야기가 담겨 있군요.']],{effect:s=>s.warLetters39=true}),
 r('meeting','말을 믿지 않는 두 사람','derenmaze38','scoll',[['matilda','증거를 보여 준다더니 우리 둘을 같은 곳으로 불렀어?'],['scoll','이런 장난으로 카디쟈님을 모욕할 생각이냐!'],['you','말을 끝까지 들어요. 정 못 믿겠다면 한꺼번에 덤벼요. 상대해 줄 테니.']],{pos:[500,390],battle:'witnessDuel39'}),
 r('hide','동상 뒤의 두 증인','derenmaze38','matilda',[['you','이제 잠깐만 동상 뒤에 숨어 있어. 헝거가 직접 말할 거야.'],['matilda','또 거짓말이면 가만두지 않을 거야.'],['scoll','듣고는 있겠다. 설명할 기회는 이번 한 번이다.']],{pos:[500,390],effect:s=>s.witnessesHidden39=true}),
 r('disguise','데빌아이의 모습으로','derenmaze38','disguise39',[['narrator','물약을 마시자 수많은 눈과 긴 망토가 몸을 감쌌다.'],['you','이제 데빌아이처럼 말해야 해. 두 사람이 들을 수 있을 만큼 또렷하게.']],{fixture:true,pos:[520,330],requires:{disguise39:1},effect:s=>{m.take(s,'disguise39');s.devileyeDisguise39=true;}}),
 r('confession','헝거의 자백','derenmaze38','hunger',[['hunger','무슨 일이냐, 데빌아이. 이곳까지 나를 불러내고.'],['you','계획을 다시 확인하지. 두 왕국에 무슨 짓을 했었지?'],['hunger','넌 지금 지하궁전 크노스의 미노타우로스 악마의 군대를 이끌 준비를 하고 있잖아.'],['hunger','아즈카 대마왕과 네가 세운 계획이잖아. 내가 데런 왕국의 옥새를 훔친 다음, 마법사 도시의 켈리에게 주문한 아수리아의 모조 검을 일부러 이곳에 떨어뜨려 데런과 아수리아의 전쟁을 유도했다.'],['narrator','동상 뒤에서 마틸다가 숨을 들이켰다. 스콜도 더는 반박하지 않았다.']],{pos:[520,330],effect:s=>{s.warConfession39=true;s.devileyeDisguise39=false;}}),
 r('final','세 사람이 함께 막아선 길','derenmaze38','hunger',[['you','두 사람 모두 똑똑히 들었지?'],['matilda','옥새를 훔친 게 너였어! 우리를 이용하다니!'],['scoll','내가… 저런 거짓 증거에 속았단 말인가.'],['hunger','데빌아이가 아니었어? 비켜라!'],['you','이번에는 혼자가 아니야. 옥새를 두고 가!']],{pos:[520,330],battle:'hungerFinal39'}),
 r('seal','헝거가 떨어뜨린 옥새','derenmaze38','seal39',[['narrator','달아난 헝거의 발밑에 데런 왕국의 옥새가 남아 있었다.'],['matilda','틀림없어. 우리 왕국의 옥새야.'],['scoll','아수리아에도 곧바로 알리겠다. 더는 싸울 이유가 없어.']],{fixture:true,pos:[520,330],effect:s=>m.give(s,'seal39')}),
 r('return','오해가 풀린 두 왕국','kingdom','caesar',[['you','옥새를 되찾았습니다. 마틸다와 스콜 선생님이 범인의 자백을 직접 들었어요.'],['matilda','아수리아가 한 일이 아니었어요. 우리가 속았어요.'],['caesar','그렇다면 군대를 물리겠다. 이미 상처 입은 백성들을 먼저 돌봐야겠구나.']],{requires:{seal39:1},effect:s=>{m.take(s,'seal39');s.warEnded39=true;}}),
 r('report','전쟁을 멈춘 증언','principal','morris',[['morris','확인되지 않은 의심이 얼마나 큰 싸움이 되는지 보았겠지.'],['you','검의 모양도, 휴전 약속도 겉만 보고 믿을 수 없었어요. 끝까지 확인해서 다행이에요.'],['morris','서로를 믿기까지는 시간이 더 필요하겠지만, 오늘은 귀한 목숨들을 지켜 냈다.']],{reward:220,ending:'헝거의 자백과 되찾은 옥새로 두 왕국의 오해를 풀었습니다. 태양 기사단의 진격이 멈추고 전쟁이 끝났습니다.'})
 ];
 const c=m.register(39,'데런 왕국의 미로 2부 · 전쟁의 배후',rows,{asuriaTruce39:false,derenTruce39:false,warLetters39:false,witnessesHidden39:false,devileyeDisguise39:false,warConfession39:false,warEnded39:false});
 const fight=(id,name,next,enemies,allies=[])=>x.encounters[id]={name,bg:'assets/maps-hires/forest-battle.png',next:c.keys[next],xp:580,gold:150,sp:70,enemies,allies};
 fight('maze39','흔적을 지키는 미로의 몬스터','swords',x.encounters.maze38.enemies,[h.aaron]);
 fight('scoll39','카디쟈 앞을 막은 스콜','cardiaRequest',[h.npc('스콜','scoll',2300,1)],[h.aaron]);
 fight('villains39','서문의 헝거와 데빌아이','suspects',[{name:'헝거',hp:1700,maxHp:1700,atk:32,element:1,sprite:'hunger',height:165},{name:'데빌아이',hp:1900,maxHp:1900,atk:34,element:3,artPath:'assets/restored/devileye-sprite.png',height:160}],[h.aaron]);
 fight('witnessDuel39','미로의 두 증인 · 스콜과 마틸다','hide',[h.npc('스콜','scoll',1800,1),h.npc('마틸다','matilda',1650)]);
 fight('hungerFinal39','자백을 들은 세 사람','seal',[{name:'헝거',hp:3000,maxHp:3000,atk:34,element:1,sprite:'hunger',height:180}],[h.ally('scoll','스콜','npc_007_도트_스콜'),{id:'matilda',npc:'matilda',name:'마틸다',hp:900,maxHp:900,atk:52,skill:'attack',sprite:'assets/original/character/friend/마틸다.png'}]);
 const before=x.interact;x.interact=(e,a)=>{const s=a.state;if((s.stage===c.keys.cardiaDelivery&&e.id==='cardia'||s.stage===c.keys.derenDelivery&&e.id==='edward')&&(s.inv.hipotion||0)<10){a.talk([['you',`고급 체력 물약이 열 개 필요해. 지금은 ${s.inv.hipotion||0}개야. 사무엘이나 압둘라에게서 슈퍼체력물약을 구해 오자.`]]);return true;}return before(e,a);};
 x.map.push(['dragonValley39','아기 대지용의 계곡',[170,420]],['westgate39','금단의 서문 · 설원',[170,420]]);
 for(const[id,name,bg]of [['dragonValley39','아기 대지용의 계곡','assets/maps-hires/forest-battle.png'],['westgate39','금단의 서문 · 설원','assets/maps-hires/ice-village.png']])x.scenes[id]=(s,n,p)=>({id,name,bg,w:960,h:540,zoom:1.1,nodes:[[170,420],[310,370],[460,350],[620,310],[780,350]],edges:[[0,1],[1,2],[2,3],[3,4]],entities:[p('back','학교 앞',170,420,'campus',[180,430])]});
})();
