/* Reference: user's original dialogue, character/inventory and spell windows. */
window.ARPIA_CLASSIC=(()=>{
 const tabs=[['status','내 정보'],['pet','펫 정보'],['magic','마법'],['inventory','아이템'],['journal','미션']];
 const gear=[{id:'staff',name:'속성 지팡이',slot:'무기',icon:0,physical:7,magic:4,cost:0},{id:'boots',name:'메탈 슈즈',slot:'신발',icon:1,agility:2,cost:120},{id:'robe',name:'마법사 로브',slot:'몸통',icon:2,magicDefense:5,cost:150},{id:'gloves',name:'가죽 장갑',slot:'손',icon:3,physicalDefense:3,cost:80},{id:'pendant',name:'사파이어 목걸이',slot:'목',icon:4,magic:5,cost:180},{id:'hat',name:'마법사 모자',slot:'머리',icon:5,magicDefense:3,cost:90}];
 for(const g of gear){ARPIA_EXTRA.defaults['own_'+g.id]=false;ARPIA_EXTRA.defaults['equip_'+g.id]=g.id==='staff';}
 let itemFilter='all';
 const icon=i=>`<span class="equipment-icon equipment-${i}" aria-hidden="true"></span>`;
 function bonuses(s){const b={physical:0,magic:0,physicalDefense:0,magicDefense:0,agility:0};for(const g of gear)if(s['equip_'+g.id]&&(g.id==='staff'?s.wand:s['own_'+g.id]))for(const k of Object.keys(b))b[k]+=g[k]||0;return b;}
 function render(kind,old,a){if(!tabs.some(t=>t[0]===kind))return old;const s=a.state,c=a.stats();let body=old;
 if(kind==='inventory'&&!window.ARPIA_SYS){
   const owned=gear.filter(g=>g.id==='staff'?s.wand:s['own_'+g.id]);
   const questArt={'스콜의 선물':'scoll-gift','웨일라 특선':'recipe-book','500년 묵은 간장':'soy-jar','평온의 불':'peace-fire','쥬다의 큰 솥':'cooking-pot','백년 동굴게':'cave-crab','오당카의 간장게장':'soy-crab-dish','마법 휴지':'magic-tissue','프리드의 거울':'frieds-mirror','모리스의 십자수':'morris-cross-stitch','네비니움':'navinium','텔레포트 좌표':'teleport-compass','침묵의 검 묶음':'silence-swords','쟈칼의 호리병':'jackal-flask','얼음 마을의 문장':'ice-crest','오염된 쿨스톤':'coolstone','고서 도서관 열쇠':'ice-crest','고대 얼음 마법서':'ancient-ice-book','얼음 케이크':'ice-cake'};
   const entries=[...owned.map(g=>({name:g.name,cat:'gear',html:`<button class="item-cell" data-gear="${g.id}" title="${g.name}">${icon(g.icon)}<small>${s['equip_'+g.id]?'장착':''}</small></button>`})),{cat:'consume',html:`<button class="item-cell" id="use-potion" title="HP 55 회복약">${icon(6)}<small>회복약 ${s.potions}</small></button>`},{cat:'consume',html:`<button class="item-cell" id="use-ether" title="MP 18 마력약">${icon(7)}<small>마력약 ${s.ethers}</small></button>`},...(a.questItems()).map(([name,desc])=>({cat:'mission',html:`<button class="item-cell quest-cell" title="${name} · ${desc}">${questArt[name]?`<img src="assets/${questArt[name]}.png" alt="">`:'<span>✧</span>'}<small>${name}</small></button>`}))].filter(e=>itemFilter==='all'||itemFilter===e.cat);
   body=`<div class="inventory-layout"><div class="paperdoll"><img src="${a.portrait('you')}" alt="장비 착용 인물">${gear.map((g,i)=>`<button class="equip-slot slot-${i}" data-unequip="${g.id}" title="${g.slot} · ${s['equip_'+g.id]?g.name:'비어 있음'}">${s['equip_'+g.id]?icon(g.icon):g.slot}</button>`).join('')}</div><div class="inventory-right"><div class="compact-stats">HP ${s.hp}/${s.maxHp}　MP ${s.mp}/${s.maxMp}<br>물리 공격 ${c.physical}　마법 공격 ${c.magic}<br>물리 방어 ${c.physicalDefense}　마법 방어 ${c.magicDefense}　민첩 ${c.agility}</div><div class="subtabs">${[['all','전체아이템'],['gear','장비아이템'],['consume','소비아이템'],['mission','미션아이템']].map(([id,label])=>`<button data-filter="${id}" class="${itemFilter===id?'active':''}">${label}</button>`).join('')}</div><div class="item-grid">${entries.map(e=>e.html).join('')}${Array.from({length:Math.max(0,18-entries.length)},()=>'<span class="item-cell empty"></span>').join('')}</div><div id="item-detail">장비를 선택하면 장착합니다. 장착 칸을 누르면 해제합니다.</div></div></div>`;
  }
  if(kind==='magic'&&!window.ARPIA_SYS)body=`<div class="magic-summary"><div>마력 ${s.mp} / ${s.maxMp}<div class="meter mp"><i style="width:${s.mp/s.maxMp*100}%"></i></div></div><div>${['불꽃마법','얼음마법','대지마법'].map((n,i)=>`<label>${n}<progress max="3" value="${s.element===i?s.spellLevel:0}"></progress>${s.element===i?Math.round(s.spellLevel/3*100):0}%</label>`).join('')}</div></div><div class="subtabs"><button data-magic-filter="all" class="active">전체마법</button><button data-magic-filter="element">${['불꽃','얼음','대지'][s.element]}마법</button><button data-magic-filter="neutral">비속성마법</button></div><div id="magic-list">${old}</div>`;
  if(kind==='journal')body=`<div class="subtabs"><button id="main-missions" class="active">메인 미션</button><button id="free-missions">프리 미션</button></div><div id="mission-content">${old}</div>`;
  return `<div class="classic-tabs">${tabs.map(([id,name])=>`<button data-classic-tab="${id}" class="${kind===id?'active':''}">${name}</button>`).join('')}</div><div class="classic-body">${body}</div><div class="classic-bottom"><span>${s.gold} 핀　·　선행 점수 ${s.sp}</span><button id="classic-close">닫기</button></div>`;
 }
 function bind(kind,a){document.querySelectorAll('[data-magic-filter]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-magic-filter]').forEach(t=>t.classList.toggle('active',t===b));document.querySelectorAll('#magic-list .item-row').forEach(row=>{const neutral=!!row.querySelector('#learn-heal');row.hidden=b.dataset.magicFilter!=='all'&&(b.dataset.magicFilter==='neutral'?!neutral:neutral);});});document.querySelectorAll('[data-classic-tab]').forEach(b=>b.onclick=()=>a.openPanel(b.dataset.classicTab));document.getElementById('classic-close')?.addEventListener('click',a.close);
  if(!window.ARPIA_SYS){document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{itemFilter=b.dataset.filter;a.openPanel('inventory');});
  document.querySelectorAll('[data-gear]').forEach(b=>b.onclick=()=>{a.state['equip_'+b.dataset.gear]=true;a.save();a.update();a.openPanel('inventory');});
  document.querySelectorAll('[data-unequip]').forEach(b=>b.onclick=()=>{a.state['equip_'+b.dataset.unequip]=false;a.save();a.update();a.openPanel('inventory');});}
  document.getElementById('free-missions')?.addEventListener('click',()=>{document.getElementById('mission-content').innerHTML=window.ARPIA_FREE.panel(a.state);document.getElementById('main-missions').classList.remove('active');document.getElementById('free-missions').classList.add('active');window.ARPIA_FREE.bind(a);});document.getElementById('main-missions')?.addEventListener('click',()=>a.openPanel('journal'));
 }
 return{gear,bonuses,render,bind};
})();
